### ISSUE TITLE
Where/How can I obtain/build the file ndc_metadata.json?

### ISSUE THREAD

**Issue by carlos3dx** [CliBench/CliBench#1]
Hello,

I'm trying to use the create_data_clibench_2 notebook but there are some required files from a folder called code_sys. Obtaining the LOINC ones was easy but I cannot find the required ndc_metadata.json with the NDC and ATC codes.

Where/How can I find/request/build the ndc_metadata.json?

Thanks in advance.

**Comment by mdkma** [comment]
Thanks a lot for reminding us about this issue! I just updated the README to include the download link for the `ndc_metadata.json` file. Please let me know if there are other issues when running the code. Thanks!

https://github.com/CliBench/CliBench/commit/262653dad285309066ec06dc1ae194a2424a950e
